// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.1
// 	protoc        v5.29.2
// source: llmproxy.proto

package llmproxy

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LLMRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jwt           string                 `protobuf:"bytes,1,opt,name=jwt,proto3" json:"jwt,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Uuid          string                 `protobuf:"bytes,3,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LLMRequest) Reset() {
	*x = LLMRequest{}
	mi := &file_llmproxy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LLMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LLMRequest) ProtoMessage() {}

func (x *LLMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_llmproxy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LLMRequest.ProtoReflect.Descriptor instead.
func (*LLMRequest) Descriptor() ([]byte, []int) {
	return file_llmproxy_proto_rawDescGZIP(), []int{0}
}

func (x *LLMRequest) GetJwt() string {
	if x != nil {
		return x.Jwt
	}
	return ""
}

func (x *LLMRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *LLMRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type LLMReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jwt           string                 `protobuf:"bytes,1,opt,name=jwt,proto3" json:"jwt,omitempty"`
	Response      string                 `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"`
	Uuid          string                 `protobuf:"bytes,3,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LLMReply) Reset() {
	*x = LLMReply{}
	mi := &file_llmproxy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LLMReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LLMReply) ProtoMessage() {}

func (x *LLMReply) ProtoReflect() protoreflect.Message {
	mi := &file_llmproxy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LLMReply.ProtoReflect.Descriptor instead.
func (*LLMReply) Descriptor() ([]byte, []int) {
	return file_llmproxy_proto_rawDescGZIP(), []int{1}
}

func (x *LLMReply) GetJwt() string {
	if x != nil {
		return x.Jwt
	}
	return ""
}

func (x *LLMReply) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

func (x *LLMReply) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

var File_llmproxy_proto protoreflect.FileDescriptor

var file_llmproxy_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x6c, 0x6c, 0x6d, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x6c, 0x6c, 0x6d, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74,
	0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4c, 0x0a, 0x0a, 0x4c, 0x4c, 0x4d, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6a, 0x77, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6a, 0x77, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x75, 0x75, 0x69, 0x64, 0x22, 0x4c, 0x0a, 0x08, 0x4c, 0x4c, 0x4d, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x10, 0x0a, 0x03, 0x6a, 0x77, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6a, 0x77, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75,
	0x75, 0x69, 0x64, 0x32, 0x84, 0x01, 0x0a, 0x08, 0x4c, 0x4c, 0x4d, 0x50, 0x72, 0x6f, 0x78, 0x79,
	0x12, 0x3d, 0x0a, 0x0b, 0x53, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x14, 0x2e, 0x6c, 0x6c, 0x6d, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2e, 0x4c, 0x4c, 0x4d, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12,
	0x39, 0x0a, 0x09, 0x53, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x12, 0x2e, 0x6c,
	0x6c, 0x6d, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2e, 0x4c, 0x4c, 0x4d, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x42, 0x10, 0x5a, 0x0e, 0x2e, 0x2f,
	0x70, 0x6b, 0x67, 0x2f, 0x6c, 0x6c, 0x6d, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_llmproxy_proto_rawDescOnce sync.Once
	file_llmproxy_proto_rawDescData = file_llmproxy_proto_rawDesc
)

func file_llmproxy_proto_rawDescGZIP() []byte {
	file_llmproxy_proto_rawDescOnce.Do(func() {
		file_llmproxy_proto_rawDescData = protoimpl.X.CompressGZIP(file_llmproxy_proto_rawDescData)
	})
	return file_llmproxy_proto_rawDescData
}

var file_llmproxy_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_llmproxy_proto_goTypes = []any{
	(*LLMRequest)(nil),    // 0: llmproxy.LLMRequest
	(*LLMReply)(nil),      // 1: llmproxy.LLMReply
	(*emptypb.Empty)(nil), // 2: google.protobuf.Empty
}
var file_llmproxy_proto_depIdxs = []int32{
	0, // 0: llmproxy.LLMProxy.SendRequest:input_type -> llmproxy.LLMRequest
	1, // 1: llmproxy.LLMProxy.SendReply:input_type -> llmproxy.LLMReply
	2, // 2: llmproxy.LLMProxy.SendRequest:output_type -> google.protobuf.Empty
	2, // 3: llmproxy.LLMProxy.SendReply:output_type -> google.protobuf.Empty
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_llmproxy_proto_init() }
func file_llmproxy_proto_init() {
	if File_llmproxy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_llmproxy_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_llmproxy_proto_goTypes,
		DependencyIndexes: file_llmproxy_proto_depIdxs,
		MessageInfos:      file_llmproxy_proto_msgTypes,
	}.Build()
	File_llmproxy_proto = out.File
	file_llmproxy_proto_rawDesc = nil
	file_llmproxy_proto_goTypes = nil
	file_llmproxy_proto_depIdxs = nil
}
