// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.2
// source: llmproxy.proto

package llmproxy

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LLMProxy_SendRequest_FullMethodName = "/llmproxy.LLMProxy/SendRequest"
	LLMProxy_SendReply_FullMethodName   = "/llmproxy.LLMProxy/SendReply"
)

// LLMProxyClient is the client API for LLMProxy service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LLMProxyClient interface {
	SendRequest(ctx context.Context, in *LLMRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	SendReply(ctx context.Context, in *LLMReply, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type lLMProxyClient struct {
	cc grpc.ClientConnInterface
}

func NewLLMProxyClient(cc grpc.ClientConnInterface) LLMProxyClient {
	return &lLMProxyClient{cc}
}

func (c *lLMProxyClient) SendRequest(ctx context.Context, in *LLMRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, LLMProxy_SendRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lLMProxyClient) SendReply(ctx context.Context, in *LLMReply, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, LLMProxy_SendReply_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LLMProxyServer is the server API for LLMProxy service.
// All implementations must embed UnimplementedLLMProxyServer
// for forward compatibility.
type LLMProxyServer interface {
	SendRequest(context.Context, *LLMRequest) (*emptypb.Empty, error)
	SendReply(context.Context, *LLMReply) (*emptypb.Empty, error)
	mustEmbedUnimplementedLLMProxyServer()
}

// UnimplementedLLMProxyServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLLMProxyServer struct{}

func (UnimplementedLLMProxyServer) SendRequest(context.Context, *LLMRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendRequest not implemented")
}
func (UnimplementedLLMProxyServer) SendReply(context.Context, *LLMReply) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendReply not implemented")
}
func (UnimplementedLLMProxyServer) mustEmbedUnimplementedLLMProxyServer() {}
func (UnimplementedLLMProxyServer) testEmbeddedByValue()                  {}

// UnsafeLLMProxyServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LLMProxyServer will
// result in compilation errors.
type UnsafeLLMProxyServer interface {
	mustEmbedUnimplementedLLMProxyServer()
}

func RegisterLLMProxyServer(s grpc.ServiceRegistrar, srv LLMProxyServer) {
	// If the following call pancis, it indicates UnimplementedLLMProxyServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LLMProxy_ServiceDesc, srv)
}

func _LLMProxy_SendRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LLMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LLMProxyServer).SendRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LLMProxy_SendRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LLMProxyServer).SendRequest(ctx, req.(*LLMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LLMProxy_SendReply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LLMReply)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LLMProxyServer).SendReply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LLMProxy_SendReply_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LLMProxyServer).SendReply(ctx, req.(*LLMReply))
	}
	return interceptor(ctx, in, info, handler)
}

// LLMProxy_ServiceDesc is the grpc.ServiceDesc for LLMProxy service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LLMProxy_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "llmproxy.LLMProxy",
	HandlerType: (*LLMProxyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendRequest",
			Handler:    _LLMProxy_SendRequest_Handler,
		},
		{
			MethodName: "SendReply",
			Handler:    _LLMProxy_SendReply_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "llmproxy.proto",
}
